In [ ]:
#，譬如逻辑回归，支持向量机，神经 网络，无量纲化可以加快求解速度；
#而在距离类模型，譬如K近邻，K-Means聚类中，无量纲化可以帮我们提升模 型精度，避免某一个取值范围特别大的特征对距离计算造成影响。
#（一个特例是决策树和树的集成算法们，对决策 树我们不需要无量纲化，决策树可以把任意数据都处理得很好。）

In [1]:
from sklearn.preprocessing import MinMaxScaler
 
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
 
#不太熟悉numpy的小伙伴，能够判断data的结构吗？ #如果换成表是什么样子？ 
import pandas as pd 
pd.DataFrame(data)


0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

In [2]:
#实现归一化 
scaler = MinMaxScaler()                             #实例化 
scaler = scaler.fit(data)                           #fit，在这里本质是生成min(x)和max(x) 
result = scaler.transform(data)                     #通过接口导出结果 result
result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [3]:
result_ = scaler.fit_transform(data)                #训练和导出结果一步达成
result_

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [4]:
scaler.inverse_transform(result)                    #将归一化后的结果逆转

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [6]:
#使用MinMaxScaler的参数feature_range实现将数据归一化到[0,1]以外的范围中
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]] 
scaler = MinMaxScaler(feature_range=[5,10])         #依然实例化 

result = scaler.fit_transform(data)                 #fit_transform一步导出结果 
result

array([[ 5.  ,  5.  ],
       [ 6.25,  6.25],
       [ 7.5 ,  7.5 ],
       [10.  , 10.  ]])

In [ ]:
#当X中的特征数量非常多的时候，fit会报错并表示，数据量太大了我计算不了 #此时使用partial_fit作为训练接口 
#scaler = scaler.partial_fit(data)

In [ ]:
#当数据(x)按均值(μ)中心化后，再按标准差(σ)缩放，数据就会服从为均值为0，方差为1的正态分布（即标准正态分 布），
#而这个过程，就叫做数据标准化(Standardization，又称Z-score normalization)

In [7]:
from sklearn.preprocessing import StandardScaler 
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
 
scaler = StandardScaler()                           #实例化 
scaler.fit(data)                                    #fit，本质是生成均值和方差

StandardScaler(copy=True, with_mean=True, with_std=True)

In [8]:
scaler.mean_                                        #查看均值的属性mean_ 

array([-0.125,  9.   ])

In [10]:
scaler.var_                                         #查看方差的属性var_

array([ 0.546875, 35.      ])

In [11]:
x_std = scaler.transform(data)                      #通过接口导出结果

In [12]:
x_std

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [13]:
x_std.mean()                                        #导出的结果是一个数组，用mean()查看均值 

0.0

In [14]:
x_std.std()                                         #用std()查看方差

1.0

In [17]:
scaler.fit_transform(data)                          #使用fit_transform(data)一步达成结果

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [16]:
scaler.inverse_transform(x_std)                     #使用inverse_transform逆转标准化

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [18]:
#看情况。大多数机器学习算法中，会选择StandardScaler来进行特征缩放，因为MinMaxScaler对异常值非常敏感。
#在PCA，聚类，逻辑回归，支持向量机，神经网络这些算法中，StandardScaler往往是最好的选择

In [ ]:
#MinMaxScaler在不涉及距离度量、梯度、协方差计算以及数据需要被压缩到特定区间时使用广泛，
#比如数字图像 处理中量化像素强度时，都会使用MinMaxScaler将数据压缩于[0,1]区间之中。 