In [12]:
import pandas as pd 

data = pd.read_csv(r"C:\Users\REGGIE\Desktop\student\数据分析资料\机器学习\02.2019年Scikit-learn的机器学习\00.配套资料\03数据预处理和特征工程\03数据预处理和特征工程\Narrativedata.csv",index_col=0)
 
data.head() 

Age     Sex Embarked Survived
0  22.0    male        S       No
1  38.0  female        C      Yes
2  26.0  female        S      Yes
3  35.0  female        S      Yes
4  35.0    male        S       No

In [14]:
data.dropna(axis = 0, inplace = True)

In [15]:
data_2 = data.copy()

In [16]:
data_2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 0 to 890
Data columns (total 4 columns):
Age         712 non-null float64
Sex         712 non-null object
Embarked    712 non-null object
Survived    712 non-null object
dtypes: float64(1), object(3)
memory usage: 27.8+ KB


In [17]:
#根据阈值将数据二值化（将特征值设置为0或1），用于处理连续型变量。大于阈值的值映射为1，而小于或等于阈 值的值映射为0。
#默认阈值为0时，特征中所有的正值都映射到1
from sklearn.preprocessing import Binarizer 
X = data_2.iloc[:,0].values.reshape(-1,1)  #类为特征专用，所以不能使用一维数组 

In [18]:
transformer = Binarizer(threshold=30).fit_transform(X)
transformer 

array([[0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],

In [19]:
data_2.iloc[:,0] = transformer

In [ ]:
#这是将连续型变量划分为分类变量的类，能够将连续型变量排序后按顺序分箱后编码。

In [20]:
from sklearn.preprocessing import KBinsDiscretizer

In [21]:
X = data.iloc[:,0].values.reshape(-1,1) 
est = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='uniform') 

est.fit_transform(X)
 


array([[0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [0.],
       [0.],
       [2.],
       [0.],
       [1.],
       [0.],
       [2.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [2.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [2.],
       [2.],
       [0.],
       [1.],
       [1.],

In [22]:
#查看转换后分的箱：变成了一列中的三箱 

set(est.fit_transform(X).ravel())
 


{0.0, 1.0, 2.0}

In [23]:
#查看转换后分的箱：变成了哑变量 
est = KBinsDiscretizer(n_bins=3, encode='onehot', strategy='uniform') 
est.fit_transform(X).toarray()

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])